### ISSUE TITLE
Variant to return all matching paths

### ISSUE THREAD

**Issue by LPGhatguy** [harryfei/which-rs#19]
`which` has the `-a` flag, which returns a list of _all_ of the executables that were found in PATH order instead of just the first one.

For some applications, it's useful to know if there were multiple options for a path being resolved.

In my case, I'm working on a toolchain manager and want to fall back to a system-wide installation of a tool under certain circumstances. In order to do that, I want to resolve my own executable name with `which`, but skip my own path.

**Comment by harryfei** [comment]
It's ok to add this feature in `which` crate. Do you want to work on it? Any PR will be appreciated.

**Comment by LPGhatguy** [comment]
I don't think I have the time to work on this feature, I'm sorry! I found a different solution to the problem I was trying to solve that does not involve doing PATH resolution myself.
