### ISSUE TITLE
Find Windows exe's at reparse points

### ISSUE THREAD

**Issue by fdncred** [harryfei/which-rs#22]
On Windows 10, any file in `c:\Users\<username>\AppData\Local\Microsoft\WindowsApps` is in the Windows path. If you do a `dir /aL` there you can see that there are files that appear to have `0 byte` file lengths. That is because they are all reparse points. It appears that `which::which(name).is_ok()` fails where `name` is one of these reparse point files. Are there any know work-arounds for this?

I've tried with which v3 and v4 and both fail. The error looks like this when I try to call winget.
```
error: Command not found
  ┌─ shell:1:1
  │
1 │ winget --help
  │ ^^^^^^ command not found
```

This is related to https://github.com/nushell/nushell/issues/1935
Thanks.

**Comment by thejpster** [comment]
I think it's this call here: https://github.com/harryfei/which-rs/blob/master/src/checker.rs#L42

Reparse points return error for 'metadata' but Ok for 'symlink_metadata'. See https://github.com/nushell/nushell/issues/1935#issuecomment-643378829

**Comment by harryfei** [comment]
Use `symlink_metadata` instead of `metadata` looks good to me. PR is welcome.

**Comment by fdncred** [comment]
Added PR #23 to address this. Thanks to @thejpster for pointing it out.

**Comment by harryfei** [comment]
New version released.
