### ISSUE TITLE
wasm32-wasi support?

### ISSUE THREAD

**Issue by mpizenberg** [harryfei/which-rs#31]
Hi, first thank you very much for this crate!

I'm building a rust program calling other executables and using `which` to locate them in order to pass the absolute path in a `Command` to avoid interference with `.current_dir()`. I'd love to be able to compile my program to the wasm32-wasi target but it seems `which` does not support that. Do you think it could make sense to support it? Would it even be possible?

**Comment by harryfei** [comment]
which use `std::fs` filesystem api, do wasm support filesystem? 
Do you really need a binary finder(what `which` does) in wasm? :confused:

**Comment by mpizenberg** [comment]
Wasm on its own does not know about a file system. There is a [WASI](https://wasi.dev/) (WebAssembly System Interface) spec that enables system calls for web assembly modules if the runtime implements it. And some runtimes do, such as [wasmtime](https://wasmtime.dev/) and [wasmer](https://wasmer.io/). So I'm evaluating if providing a wasm32-wasi version of my executable would make sense for people that would want to run it via wasmtime or wasmer.

I'm developing a [tests runner](https://github.com/mpizenberg/elm-test-rs) for the elm language, so it needs to call the `elm` binary at some point. It also needs to call `node` to run the tests, which are generated JS files.

I totally understand if you think it's not worth the trouble. I don't know how `which` is implemented, and maybe that's not even possible. When I'm compiling with `--target wasm32-wasi`, I get errors for missing `is_valid` and `append_extension`. Looking at those functions, it seems ambiguous to port to wasi, because we don't know the host system at compile time, which is the nice thing of wasm-wasi. Possible solutions would involve runtime heuristics to detect the host system, or a different function for wasi that would have to pass potential extensions as arguments?

**Comment by harryfei** [comment]
Oh, I forget that we can run wasm in a host environment(not just in web browser) :).
I'm open to this idea.

**Comment by mpizenberg** [comment]
Yep, they like to joke that "wasm is neither Web, nor assembly" :)
I'll try to have a look at it when I get some time then, to let you know what could make sense.

**Comment by jcaesar** [comment]
I'm wondering what kind of runtime heuristics you're talking about. WASI exists to make you not need to care about what the host system is, so there isn't really any way to detect it. The only think I can imagine is "look for antyhing with a related name, `.exe` or not". Btw, you can't check for executability with WASI because it can't check files' owners/permissions. You also can't spawn another process because there's no API for that either. Honestly, I don't think making which actually work is realistic or useful.

So why did I make a PR? Because which is a dependency of crates that do otherwise work on wasm32-wasi, `clearscreen` for example.

**Comment by haruhikonyan** [comment]
Would it be possible to support wasm32-unknown-unknown?

**Comment by jcaesar** [comment]
Technically, you can just change https://github.com/harryfei/which-rs/blob/e5ec71143965a7c7751c853fb229cb973bfcaa13/src/checker.rs#L27 to 
```rust
#[cfg(any(windows, all(target_family = "wasm", target_os = "unknown")]
```
or maybe even
```rust
#[cfg(not(any(unix, target_os = "wasi")))] // (now compiles on any target)
```


But whether that's meaningful, and whether to return true, false, or to panic on `wasm32-unknown-unknown` is beyond me.
