### ISSUE TITLE
Possibility to change the error message

### ISSUE THREAD

**Issue by Ebedthan** [harryfei/which-rs#36]
Hi,

I'm trying to find a way to change the error message outputted by `which::which` when no match is found to include more helpful information for the user. I have looked to `std::error::Error::source()` but cannot find a way.

Any help will be greatly appreciated.

Thanks

**Comment by Xaeroxe** [comment]
I'm going to assume that this issue is too old for me to help now. If I'm wrong please reopen this and explain.
