### ISSUE TITLE
Allow walking over all executables in PATH

### ISSUE THREAD

**Issue by Fuuzetsu** [harryfei/which-rs#37]
`which` is great if you want to find a binary you know the full name of. It's less great if you are trying to find one of many executables.

For example, I'm trying to find any executable binary that starts with `fooBar`. I can't do this with `which`.

This crate can already walk over all the executables: it'd be great if we could get hold of this iterator and do a custom test.

**Comment by harryfei** [comment]
You can add your custom checker in which's current design.
Like this: 
https://github.com/harryfei/which-rs/blob/2c54067bab846e96f07be60e78250f385825f09f/src/lib.rs#L86-L93

Does it match your case?

The only changes we should make is exporting `checker` and `finder` to public.
https://github.com/harryfei/which-rs/blob/2c54067bab846e96f07be60e78250f385825f09f/src/lib.rs#L29
https://github.com/harryfei/which-rs/blob/2c54067bab846e96f07be60e78250f385825f09f/src/lib.rs#L31

**Comment by Fuuzetsu** [comment]
I think that doesn't really work because `finder.find` basically gives the checker every value of `PATH` suffixed by `binary_name`. So it doesn't actually walk all the binaries as I'm looking to do.

After looking at the source to confirm the above however, I see now that `std::env::split_paths` is just some stdlib thing. So I think I can just implement what I want with a small function and there might not be any need to force this into `which-rs`.

It'd be cool if it existed though, not having to write the executable and existed checkers would be nice.

**Comment by marier-nico** [comment]
I think https://github.com/harryfei/which-rs/pull/40 might allow you to do this. You could try `which_re(Regex::new(r"^fooBar").unwrap())` (assuming you don't mind pulling in the `regex` crate as well).

However, the PR isn't part of a release yet. Though I think you could use a reference to this git repo instead of crates.io and it would work.

**Comment by Fuuzetsu** [comment]
> @Fuuzetsu I think #40 might allow you to do this. You could try `which_re(Regex::new(r"^fooBar").unwrap())` (assuming you don't mind pulling in the `regex` crate as well).
> 
> However, the PR isn't part of a release yet. Though I think you could use a reference to this git repo instead of crates.io and it would work.

That looks probably like something I can use. Feel free to close this issue as resolved via #40. I'm not in a rush so I will simply wait until it's released and I'll switch to it one day. Thank you.

**Comment by harryfei** [comment]
@marier-nico @Fuuzetsu New version `4.2.1` is released on `crates.io` .

**Comment by Fuuzetsu** [comment]
Thanks, I finally verified that `which_re` works and switched to using it.

**Comment by marier-nico** [comment]
Awesome, glad it proved useful in the end! 😄
