### ISSUE TITLE
Compile error in crate 4.2.3 published 1 hour a ago.

### ISSUE THREAD

**Issue by da-niao-dan** [harryfei/which-rs#48]
github.com-\which-4.2.3\src\finder.rs:161:65
    |
161 | ...                   if s.as_bytes().first() == Some(b'.') {
    |                                                       ^^^^
    |                                                       |
    |                                                       expected `&u8`, found `u8`
    |                                                       help: consider borrowing here: `&b'.'`

**Comment by harryfei** [comment]
Fixed by #50
