### ISSUE TITLE
windows: `.EXE` in returned path is capitalized for extensionless input

### ISSUE THREAD

**Issue by nayeemrmn** [harryfei/which-rs#54]
```rust
extern crate which;

use which::which;

fn main() {
  println!("{:?}", which("cargo"));
  println!("{:?}", which("cargo.exe"));
}
```
```
Ok("C:\\Users\\Nayeem\\.cargo\\bin\\cargo.EXE")
Ok("C:\\Users\\Nayeem\\.cargo\\bin\\cargo.exe")
```
Expected:
```
Ok("C:\\Users\\Nayeem\\.cargo\\bin\\cargo.exe")
Ok("C:\\Users\\Nayeem\\.cargo\\bin\\cargo.exe")
```

**Comment by rgwood** [comment]
We've run into this in Nushell and I agree that it's unexpected behaviour.

We're not performing case sensitive file checks, but we would like to show our users the file path exactly as it exists on disk.

**Comment by Xaeroxe** [comment]
Fixed in https://github.com/harryfei/which-rs/pull/61

**Comment by rgwood** [comment]
Awesome, thank you so much!

**Comment by Xaeroxe** [comment]
@harryfei I'd like to get [this](https://github.com/harryfei/which-rs/pull/61) into a release on crates.io

**Comment by harryfei** [comment]
Thanks @Xaeroxe. It's done. 
The latest version is `4.3.0`.
