### ISSUE TITLE
windows: Do not check if the extension is executable

### ISSUE THREAD

**Issue by N3xed** [harryfei/which-rs#56]
The current implementation for windows checks all executable extensions in the environment variable `PATHEXT`, **but** if the binary path already has an extension that extension is currently ignored if it is not in that environment variable.

https://github.com/harryfei/which-rs/blob/cd6add3af770fddb9231bb0d5e127062bdcf2de4/src/finder.rs#L182

I'd argue this check is detrimental as it prevents some executable files (`.py` files in my case) to be found. These files may not be executable directly but through a shell.

Now I really don't know what use cases this check has, but I'd nonetheless suggest replacing it with the following:
```rust
if p.extension().is_some() {
```
so forward the file **if** it has an extension, otherwise try all extensions in `PATHEXT` appended to file.

An alternative would be, if the extension is not in `PATH_EXTENSIONS` and file does actually have an extension, add it to the beginning of the iterator with all executable extensions:

```rust
        paths
            .into_iter()
            .flat_map(move |p| -> Box<dyn Iterator<Item = _>> {
                // Check if path already have executable extension
                if has_executable_extension(&p, &PATH_EXTENSIONS) {
                    Box::new(iter::once(p))
                } else {
                    // Appended paths with windows executable extensions.
                    // e.g. path `c:/windows/bin` will expend to:
                    // c:/windows/bin.COM
                    // c:/windows/bin.EXE
                    // c:/windows/bin.CMD
                    // ...
                    let bare_file = p.extension().map(|_| p.clone());
                    Box::new(
                        bare_file
                            .into_iter()
                            .chain(PATH_EXTENSIONS.iter().map(move |e| {
                                // Append the extension.
                                let mut p = p.clone().into_os_string();
                                p.push(e);

                                PathBuf::from(p)
                            })),
                    )
                }
            })

```

Finally, another alternative is, and this would require more effort, to make this behavior configurable.

**Comment by harryfei** [comment]
There is one question: does `xxx.py` file belong to exectuables?

**Comment by Xaeroxe** [comment]
`cmd` treats it as an executable, so I take that as a clear signal that the answer is yes.

**Comment by harryfei** [comment]
Does searching "xxx.py.EXE" is good behavior if "py" is not in `PATHEXT`?

**Comment by Xaeroxe** [comment]
Probably not. The `which` command which we are basing ourselves upon specifically states that it returns the file which would be executed if this were typed at the shell. "The shell" is technically ambiguous, but it's reasonable to infer that on Windows this would be the behavior of `cmd.exe`. `cmd.exe` won't treat `py` as executable if it isn't in the `PATHEXT`, so at minimum this would be a surprising result.

We should probably revert #57.

**Comment by Xaeroxe** [comment]
Well, wait, my `cmd.exe` is still executing `.py` files even after I remove them from my `PATHEXT`.

**Comment by Xaeroxe** [comment]
Okay, so if it's not inside `PATHEXT` Windows falls back to using the default file handler for the extension which on some systems will "execute" the file, even though technically the file is just being opened. It's worth noting it will only do this if the extension was specified at the `cmd` prompt. Which means that the behavior in #57 does in fact match `cmd`.

**Comment by harryfei** [comment]
> Okay, so if it's not inside PATHEXT Windows falls back to using the default file handler for the extension which on some systems will "execute" the file, even though technically the file is just being opened.

Does it mean we could trade every file with extension as executable file?

**Comment by Xaeroxe** [comment]
A good question! At this rate I'm not even sure what "executable" means on Windows anymore. If you double click and open a word doc you wouldn't say it's "executing" but a python script you double clicked on is definitely executing. For most files it'd be weird to open them and be like "here's your executable!" but a python script can definitely be executed by opening it.

I don't know. It feels weird to carve out an exception just for python files, as there are other script interpreters that might have a similar setup. The question is actually kind of complicated and I think there's strong justification for both approaches.

**Comment by Xaeroxe** [comment]
FWIW the Windows equivalent to `which` is `where.exe`, and `where` doesn't actually try to determine if the file is executable.

```
C:\Users\kiese>where kernel32.dll
C:\Windows\System32\kernel32.dll
```

**Comment by harryfei** [comment]
Aligning with `where.exe` maybe a good choice.
We could not decide it now. Let others leave their opinions.

**Comment by Xaeroxe** [comment]
Closed in https://github.com/harryfei/which-rs/pull/83
