### ISSUE TITLE
Request: allow not using current working directory

### ISSUE THREAD

**Issue by cgranade** [harryfei/which-rs#60]
Currently, `which::which` calls `env::current_dir` when looking for executables on `$PATH` (https://github.com/harryfei/which-rs/blob/master/src/lib.rs#L64). It would be helpful to allow bypassing the call to `current_dir`, as that would allow checking if a command is available globally. Thank you for your help and for a really useful crate! ♥

**Comment by Xaeroxe** [comment]
Added in #62
