### ISSUE TITLE
Support searching with a different PATH

### ISSUE THREAD

**Issue by schneems** [harryfei/which-rs#65]
Hello. I just found this crate and it looks great. I'm writing buildpacks with libcnb.rs and I frequently need to execute commands that are on a different path (not in `env::var_os("PATH")`.

I was going to open an issue and ask for that functionality, but I actually see you've got a struct on Git that's not yet released that I think could meet this need:

```
WhichConfig {
  binary_name: Some("whatever".into()),
  custom_path_list: Some(some_other_env_object.var("PATH")),
  ..WhichConfig::default()
}.first_result().iter()
```

It seems that's been there for a few months. Would you consider that stable to use from github? Could you release a version with that interface?

**Comment by harryfei** [comment]
@schneems Sure. 4.4.0 upgraded.

**Comment by schneems** [comment]
thanks!
