### ISSUE TITLE
OnceLock can replace the use of Lazy in the Windows implementation.

### ISSUE THREAD

**Issue by james7132** [harryfei/which-rs#89]
`std::sync::OnceLock` was stablized in Rust 1.70, which is compatible with the crate's MSRV. The dependency can be replaced with the std version fairly easily and would drop a dependency, even without `Lazy` being stabilized, via `OnceLock::get_or_init`.

**Comment by Xaeroxe** [comment]
Thanks for letting me know! This is fixed in version 6.0.1 which is now available on crates.io.
