### ISSUE TITLE
regression

### ISSUE THREAD

**Issue by njskalski** [harryfei/which-rs#91]
Hi, 

After upgrading to version 6 or 6.0.1, both IntelliJ Clion and Gitlab build runner (Debian) fail to find rust-analyzer which is clearly at 
`»ʚ which rust-analyzer
/home/andrzej/.cargo/bin/rust-analyzer`
in both bash and fish. For some reason, same program ran from command line does work, but not ran from IntelliJ. I can't tell why.

steps to reproduce (sorry for big repro):
1) checkout https://gitlab.com/njskalski/bernardo (with submodules!)
2) rustup component add rust-analyzer
3) and run from clion "show_usages_integ_test_1".

With version 5 - works.
With version 6 - fails to find rust-analyzer.
Weird.

**Comment by Xaeroxe** [comment]
So two things

1. Please don't mention Clion as a requirement in your issue if it's not required to run the unit test. You can run this just fine with `cargo test show_usages_integ_test_1` and Clion adds a ton of complexity that I don't want when I'm bug hunting.
2. I can't reproduce this. This unit test still passes after I upgrade to which 6.0.1.

```
running 1 test
test big_tests::lsp_rust_integ::show_usages_test_1::show_usages_integ_test_1_INCOMPLETE ... [2024-04-06T22:43:21Z DEBUG bernardo::config::global_editor_options] discovering location of rust-analyzer
[2024-04-06T22:43:21Z WARN  bernardo::config::global_editor_options] using rust-analyzer from "/home/jacob/.cargo/bin/rust-analyzer"
```

**Comment by Xaeroxe** [comment]
Just for good measure, I went back and ran the unit test with `which@6.0.1` using the CLion UI. I still wasn't able to reproduce the issue. If you experience further problems consider filing a bug with Clion.
